//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurakshaAutomation.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AutomationSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AutomationSettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SurakshaAutomation.Data.AutomationSettings", typeof(AutomationSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 1.
        /// </summary>
        internal static string AD1Value {
            get {
                return ResourceManager.GetString("AD1Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 2.
        /// </summary>
        internal static string AD2Value {
            get {
                return ResourceManager.GetString("AD2Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 3.
        /// </summary>
        internal static string AD3Value {
            get {
                return ResourceManager.GetString("AD3Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test@567.
        /// </summary>
        internal static string ADFPassword {
            get {
                return ResourceManager.GetString("ADFPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KLIMUM\LO7802.
        /// </summary>
        internal static string ADFSLogin {
            get {
                return ResourceManager.GetString("ADFSLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age of Insured Customer(Years).
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\D Pavan\SurakshaAutomation\TWICOAppAutomation\Data\BulkUploadErrorList.xlsx.
        /// </summary>
        internal static string BulkUploadErrorList {
            get {
                return ResourceManager.GetString("BulkUploadErrorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Type,Loan Number,Customer ID,Customer Name,Underwriting Status,Underwriting Decision,COI Issued,Is SMQ.
        /// </summary>
        internal static string CategoryList {
            get {
                return ResourceManager.GetString("CategoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERRORS.
        /// </summary>
        internal static string Downloadedcolumn {
            get {
                return ResourceManager.GetString("Downloadedcolumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\pavand\Downloads\.
        /// </summary>
        internal static string DownloadedexpectedFilePath {
            get {
                return ResourceManager.GetString("DownloadedexpectedFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Report.
        /// </summary>
        internal static string Downloadedsheetname {
            get {
                return ResourceManager.GetString("Downloadedsheetname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is mandatory.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecentActiveCasesReport.
        /// </summary>
        internal static string ExpectedDownloadedFileName_Dashboard {
            get {
                return ResourceManager.GetString("ExpectedDownloadedFileName_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MedicalCasesReport.
        /// </summary>
        internal static string ExpectedDownloadedMedicalFileName_Dashboard {
            get {
                return ResourceManager.GetString("ExpectedDownloadedMedicalFileName_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string ExplicitWait {
            get {
                return ResourceManager.GetString("ExplicitWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Sum Insured.
        /// </summary>
        internal static string FinalSIField {
            get {
                return ResourceManager.GetString("FinalSIField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goods Service Tax(in Rs.).
        /// </summary>
        internal static string GSField {
            get {
                return ResourceManager.GetString("GSField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kotak Premium(in Rs.).
        /// </summary>
        internal static string KPfield {
            get {
                return ResourceManager.GetString("KPfield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JOINTLOAN111.
        /// </summary>
        internal static string Loan_Number {
            get {
                return ResourceManager.GetString("Loan Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpectedErrorList.
        /// </summary>
        internal static string Mastercolumn {
            get {
                return ResourceManager.GetString("Mastercolumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorList.
        /// </summary>
        internal static string Mastersheetname {
            get {
                return ResourceManager.GetString("Mastersheetname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete journey in one sitting. If timed-out, please retry..
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMQ details successfully submitted.
        /// </summary>
        internal static string OTP_SuccessfullMsg {
            get {
                return ResourceManager.GetString("OTP_SuccessfullMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venky@123.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pincode.
        /// </summary>
        internal static string PincodeValue {
            get {
                return ResourceManager.GetString("PincodeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string ProductField {
            get {
                return ResourceManager.GetString("ProductField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANDRACUS.
        /// </summary>
        internal static string SearchedCustomerId {
            get {
                return ResourceManager.GetString("SearchedCustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Number.
        /// </summary>
        internal static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer ID.
        /// </summary>
        internal static string SelectCustomerId {
            get {
                return ResourceManager.GetString("SelectCustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital SMQ.
        /// </summary>
        internal static string SMQDigitalText {
            get {
                return ResourceManager.GetString("SMQDigitalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\D Pavan\SurakshaAutomation\TWICOAppAutomation\Data\CD000150_QWERT123_QWERT123_SMQ.zip.
        /// </summary>
        internal static string SMQPhysicalDataPath {
            get {
                return ResourceManager.GetString("SMQPhysicalDataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMQ has been uploaded successfully.
        /// </summary>
        internal static string SMQSuccessfulMsg {
            get {
                return ResourceManager.GetString("SMQSuccessfulMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string StateValue {
            get {
                return ResourceManager.GetString("StateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum Assured.
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenure.
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium.
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominee Assured Details.
        /// </summary>
        internal static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominee Full Name.
        /// </summary>
        internal static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominee Percent of Share.
        /// </summary>
        internal static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship with life insured.
        /// </summary>
        internal static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://d2hut3t9dvpsvu.cloudfront.net/smq?%26name=9347301244_JOINTLOAN111%26password=y%21N0V2*nrL%26loanid=JOINTLOAN111.
        /// </summary>
        internal static string TestingURL {
            get {
                return ResourceManager.GetString("TestingURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venkatesh.yada@valuemomentum.com.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underwriting Status.
        /// </summary>
        internal static string UWstatusField {
            get {
                return ResourceManager.GetString("UWstatusField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewBulkUploadReport_Life Insurance.
        /// </summary>
        internal static string ViewBulkUploadReportFileName {
            get {
                return ResourceManager.GetString("ViewBulkUploadReportFileName", resourceCulture);
            }
        }
    }
}
