//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurakshaAutomation.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SMQQuestions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SMQQuestions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SurakshaAutomation.Data.SMQQuestions", typeof(SMQQuestions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you consulted any doctor for treatment of any ailment other than common cough or cold or undergone any hospitalization or any investigations (including X rays, ECG, blood tests, biopsies, CT Scan, MRI, Ultrasonography, 2D Echo etc.) in the last 5 years? Have you been absent from work due to any illness or injury for a continuous period of more than 7 days during the last five years? *.
        /// </summary>
        internal static string Question1 {
            get {
                return ResourceManager.GetString("Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you, or have you been in close contact with COVID 19 positive person or tested positive for COVID 19 or awaiting COVID 19 test reports, or have been quarantined or undergone treatment or require regular follow up for COVID 19? *.
        /// </summary>
        internal static string Question10 {
            get {
                return ResourceManager.GetString("Question10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you experienced COVID 19 related symptoms like fever/cough/breathlessness/nausea/diarrhea within last 1 month? *.
        /// </summary>
        internal static string Question11 {
            get {
                return ResourceManager.GetString("Question11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you involved in management of COVID 19 patients or working as Health care worker? If yes, please provide Medical Specialty and exact nature of duties below. *.
        /// </summary>
        internal static string Question12 {
            get {
                return ResourceManager.GetString("Question12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you experienced or experiencing any adverse reaction post vaccination? If yes, please provide full details. *.
        /// </summary>
        internal static string Question13 {
            get {
                return ResourceManager.GetString("Question13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you travelled abroad during last 14 days or do you intend to travel abroad in next 30 days? If yes, please provide details. *.
        /// </summary>
        internal static string Question14 {
            get {
                return ResourceManager.GetString("Question14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you ever been asked by your family doctor or any physician to reduce your weight or to change your habits related to tobacco consumptions or alcohol intake? *.
        /// </summary>
        internal static string Question2 {
            get {
                return ResourceManager.GetString("Question2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you ever been diagnosed with or received treatment for any disability or medical conditions such as stroke, paralysis, epilepsy or other brain related disease, diabetes, hypertension, elevated cholesterol, any cancer, tumor, abnormal tissue growth or cyst, mental or nervous disorders including anxiety or depression, heart diseases including heart attack, chest pain, breast diseases, HIV infection or sexually transmitted disease, any thyroid disease, congenital or genetic disease or physical deformity o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Question3 {
            get {
                return ResourceManager.GetString("Question3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you ever been diagnosed with or received treatment for disease or disorder of the circulatory system, lungs or respiratory system, digestive system including liver, stomach, gall bladder, pancreas and bowel, blood including anemia, kidney, urinary bladder, prostate, genital organs, bones, joints, spine or muscle, eye, ear, nose or throat? *.
        /// </summary>
        internal static string Question4 {
            get {
                return ResourceManager.GetString("Question4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have any life insurance cover or have you applied or has any of your applications for a new cover or for reinstatement for life, health, accident, critical illness or any other rider with Kotak Mahindra Life Insurance Company Ltd. or any other insurance company in India or overseas ever been declined, postponed, withdrawn or accepted with an extra premium or reduced cover or exclusions? *.
        /// </summary>
        internal static string Question5 {
            get {
                return ResourceManager.GetString("Question5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you engage or intend to engage in any aerial flight other than a fare-paying passenger on a commercial airline, sports, races, business or occupation or any hobby of a hazardous nature such as mining, diving, mountaineering, parachuting, private aviation, racing etc.? *.
        /// </summary>
        internal static string Question6 {
            get {
                return ResourceManager.GetString("Question6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has any member of your immediate family e.g. parents, brothers, sisters suffered from or died of heart disease, stroke, high blood pressure, cancer, kidney failure, diabetes, AIDs, HIV or any other chronic or hereditary/familial disorders before the age of 60 years? *.
        /// </summary>
        internal static string Question7 {
            get {
                return ResourceManager.GetString("Question7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have any habit of smoking, chewing tobacco, alcohol, narcotics in any form in quantities consumed more than that is mentioned below? *.
        /// </summary>
        internal static string Question8 {
            get {
                return ResourceManager.GetString("Question8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are there any conviction or criminal proceedings against you in any court of law in India or abroad? *.
        /// </summary>
        internal static string Question9 {
            get {
                return ResourceManager.GetString("Question9", resourceCulture);
            }
        }
    }
}
