//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurakshaAutomation.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestCase_VerifyReferToUW {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestCase_VerifyReferToUW() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SurakshaAutomation.Data.TestCase_VerifyReferToUW", typeof(TestCase_VerifyReferToUW).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REFER TO UW.
        /// </summary>
        internal static string AfterTestUWDecision {
            get {
                return ResourceManager.GetString("AfterTestUWDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2000000.
        /// </summary>
        internal static string Annual_Income {
            get {
                return ResourceManager.GetString("Annual Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BeforeTestUWDecision {
            get {
                return ResourceManager.GetString("BeforeTestUWDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string Declaration {
            get {
                return ResourceManager.GetString("Declaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string Height_in_Feet {
            get {
                return ResourceManager.GetString("Height in Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string Inches {
            get {
                return ResourceManager.GetString("Inches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NRI/PIO.
        /// </summary>
        internal static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please answer all the Questions.
        /// </summary>
        internal static string PageWarning {
            get {
                return ResourceManager.GetString("PageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAAAA0099A.
        /// </summary>
        internal static string Pancard {
            get {
                return ResourceManager.GetString("Pancard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co-Borrower.
        /// </summary>
        internal static string Primary_Borrower_or_Co_Borrowers {
            get {
                return ResourceManager.GetString("Primary Borrower or Co-Borrowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2000000.
        /// </summary>
        internal static string SumAssured {
            get {
                return ResourceManager.GetString("SumAssured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string TotalNumberofBorrowers {
            get {
                return ResourceManager.GetString("TotalNumberofBorrowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salaried.
        /// </summary>
        internal static string Type_of_Employment {
            get {
                return ResourceManager.GetString("Type of Employment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 120.
        /// </summary>
        internal static string Weight_in_Kg {
            get {
                return ResourceManager.GetString("Weight in Kg", resourceCulture);
            }
        }
    }
}
