//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurakshaAutomation.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SurakshaAutomation.Data.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sendToKLI.
        /// </summary>
        internal static string AfterSMQTest {
            get {
                return ResourceManager.GetString("AfterSMQTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2000000.
        /// </summary>
        internal static string Annual_Income {
            get {
                return ResourceManager.GetString("Annual Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string BeforeSMQTest {
            get {
                return ResourceManager.GetString("BeforeSMQTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string Declaration {
            get {
                return ResourceManager.GetString("Declaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string Height_in_Feet {
            get {
                return ResourceManager.GetString("Height in Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string Inches {
            get {
                return ResourceManager.GetString("Inches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify OTP.
        /// </summary>
        internal static string ModalTitle {
            get {
                return ResourceManager.GetString("ModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NRI/PIO.
        /// </summary>
        internal static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please answer all the Questions.
        /// </summary>
        internal static string PageWarning {
            get {
                return ResourceManager.GetString("PageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAAAA0099A.
        /// </summary>
        internal static string Pancard {
            get {
                return ResourceManager.GetString("Pancard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co-Borrower.
        /// </summary>
        internal static string Primary_Borrower_or_Co_Borrowers {
            get {
                return ResourceManager.GetString("Primary Borrower or Co-Borrowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29-09-2021.
        /// </summary>
        internal static string Qu1_DateOfDiagnosis {
            get {
                return ResourceManager.GetString("Qu1_DateOfDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qu1_FrequencyofMedication.
        /// </summary>
        internal static string Qu1_FrequencyofMedication {
            get {
                return ResourceManager.GetString("Qu1_FrequencyofMedication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qu1_MedicationName.
        /// </summary>
        internal static string Qu1_MedicationName {
            get {
                return ResourceManager.GetString("Qu1_MedicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qu1_NatureofAilmentDisease.
        /// </summary>
        internal static string Qu1_NatureofAilmentDisease {
            get {
                return ResourceManager.GetString("Qu1_NatureofAilmentDisease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fully Recovered.
        /// </summary>
        internal static string Qu1_RecoveryStatus {
            get {
                return ResourceManager.GetString("Qu1_RecoveryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29-09-2022.
        /// </summary>
        internal static string Qu10_DateOfDiagnosis {
            get {
                return ResourceManager.GetString("Qu10_DateOfDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string Qu10_HomeQuarantined {
            get {
                return ResourceManager.GetString("Qu10_HomeQuarantined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string Qu10_Hospitalised {
            get {
                return ResourceManager.GetString("Qu10_Hospitalised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29-09-2022.
        /// </summary>
        internal static string Qu11_DateOfDiagnosis {
            get {
                return ResourceManager.GetString("Qu11_DateOfDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qu11_FrequencyofMedication.
        /// </summary>
        internal static string Qu11_FrequencyofMedication {
            get {
                return ResourceManager.GetString("Qu11_FrequencyofMedication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qu11_MedicationName.
        /// </summary>
        internal static string Qu11_MedicationName {
            get {
                return ResourceManager.GetString("Qu11_MedicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fully Recovered.
        /// </summary>
        internal static string Qu11_RecoveryStatus {
            get {
                return ResourceManager.GetString("Qu11_RecoveryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qu11_Symptoms.
        /// </summary>
        internal static string Qu11_Symptoms {
            get {
                return ResourceManager.GetString("Qu11_Symptoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qu12_MedicalSpecialty.
        /// </summary>
        internal static string Qu12_MedicalSpecialty {
            get {
                return ResourceManager.GetString("Qu12_MedicalSpecialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qu12_WhatYouDo.
        /// </summary>
        internal static string Qu12_WhatYouDo {
            get {
                return ResourceManager.GetString("Qu12_WhatYouDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qu13_AdverseReactionSymptoms.
        /// </summary>
        internal static string Qu13_AdverseReactionSymptoms {
            get {
                return ResourceManager.GetString("Qu13_AdverseReactionSymptoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qu13_FrequencyofMedication.
        /// </summary>
        internal static string Qu13_FrequencyofMedication {
            get {
                return ResourceManager.GetString("Qu13_FrequencyofMedication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qu13_MedicationName.
        /// </summary>
        internal static string Qu13_MedicationName {
            get {
                return ResourceManager.GetString("Qu13_MedicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fully Recovered.
        /// </summary>
        internal static string Qu13_RecoveryStatus {
            get {
                return ResourceManager.GetString("Qu13_RecoveryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29-09-2021.
        /// </summary>
        internal static string Qu2_DateOfDiagnosis {
            get {
                return ResourceManager.GetString("Qu2_DateOfDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qu2_FrequencyofMedication.
        /// </summary>
        internal static string Qu2_FrequencyofMedication {
            get {
                return ResourceManager.GetString("Qu2_FrequencyofMedication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qu2_MedicationName.
        /// </summary>
        internal static string Qu2_MedicationName {
            get {
                return ResourceManager.GetString("Qu2_MedicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qu2_Nature of ailment.
        /// </summary>
        internal static string Qu2_NatureofAilmentDisease {
            get {
                return ResourceManager.GetString("Qu2_NatureofAilmentDisease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fully Recovered.
        /// </summary>
        internal static string Qu2_RecoveryStatus {
            get {
                return ResourceManager.GetString("Qu2_RecoveryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29-09-2021.
        /// </summary>
        internal static string Qu3_DateOfDiagnosis {
            get {
                return ResourceManager.GetString("Qu3_DateOfDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qu3_FrequencyofMedication.
        /// </summary>
        internal static string Qu3_FrequencyofMedication {
            get {
                return ResourceManager.GetString("Qu3_FrequencyofMedication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qu3_MedicationName.
        /// </summary>
        internal static string Qu3_MedicationName {
            get {
                return ResourceManager.GetString("Qu3_MedicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qu2_NatureofAilmentDisease.
        /// </summary>
        internal static string Qu3_NatureofAilmentDisease {
            get {
                return ResourceManager.GetString("Qu3_NatureofAilmentDisease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fully Recovered.
        /// </summary>
        internal static string Qu3_RecoveryStatus {
            get {
                return ResourceManager.GetString("Qu3_RecoveryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29-09-2021.
        /// </summary>
        internal static string Qu4_DateOfDiagnosis {
            get {
                return ResourceManager.GetString("Qu4_DateOfDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qu4_FrequencyofMedication.
        /// </summary>
        internal static string Qu4_FrequencyofMedication {
            get {
                return ResourceManager.GetString("Qu4_FrequencyofMedication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qu4_MedicationName.
        /// </summary>
        internal static string Qu4_MedicationName {
            get {
                return ResourceManager.GetString("Qu4_MedicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qu4_NatureofAilmentDisease.
        /// </summary>
        internal static string Qu4_NatureofAilmentDisease {
            get {
                return ResourceManager.GetString("Qu4_NatureofAilmentDisease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fully Recovered.
        /// </summary>
        internal static string Qu4_RecoveryStatus {
            get {
                return ResourceManager.GetString("Qu4_RecoveryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qu5_InsuranceCompanyName.
        /// </summary>
        internal static string Qu5_InsuranceCompanyName {
            get {
                return ResourceManager.GetString("Qu5_InsuranceCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusions.
        /// </summary>
        internal static string Qu5_InsuranceStatus {
            get {
                return ResourceManager.GetString("Qu5_InsuranceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qu5_ReasonforYourSelection.
        /// </summary>
        internal static string Qu5_ReasonforYourSelection {
            get {
                return ResourceManager.GetString("Qu5_ReasonforYourSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qu6_ClassifyHobby.
        /// </summary>
        internal static string Qu6_ClassifyHobby {
            get {
                return ResourceManager.GetString("Qu6_ClassifyHobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qu6_ExactHobby.
        /// </summary>
        internal static string Qu6_ExactHobby {
            get {
                return ResourceManager.GetString("Qu6_ExactHobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qu7_AgeOfDiagnosis.
        /// </summary>
        internal static string Qu7_AgeOfDiagnosis {
            get {
                return ResourceManager.GetString("Qu7_AgeOfDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alive.
        /// </summary>
        internal static string Qu7_IsThePerson {
            get {
                return ResourceManager.GetString("Qu7_IsThePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qu7_Relation.
        /// </summary>
        internal static string Qu7_Relation {
            get {
                return ResourceManager.GetString("Qu7_Relation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qu7_TypeofAilment.
        /// </summary>
        internal static string Qu7_TypeofAilment {
            get {
                return ResourceManager.GetString("Qu7_TypeofAilment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string Qu8_Alcohol {
            get {
                return ResourceManager.GetString("Qu8_Alcohol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string Qu8_Cigarette {
            get {
                return ResourceManager.GetString("Qu8_Cigarette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string Qu8_Narcotics {
            get {
                return ResourceManager.GetString("Qu8_Narcotics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 123456.
        /// </summary>
        internal static string TestOTP {
            get {
                return ResourceManager.GetString("TestOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string TotalNumberofBorrowers {
            get {
                return ResourceManager.GetString("TotalNumberofBorrowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salaried.
        /// </summary>
        internal static string Type_of_Employment {
            get {
                return ResourceManager.GetString("Type of Employment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 120.
        /// </summary>
        internal static string Weight_in_Kg {
            get {
                return ResourceManager.GetString("Weight in Kg", resourceCulture);
            }
        }
    }
}
