//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurakshaAutomation.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ViewBulkUpload {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewBulkUpload() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SurakshaAutomation.Data.ViewBulkUpload", typeof(ViewBulkUpload).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string DownloadFailed {
            get {
                return ResourceManager.GetString("DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string DownloadMedical {
            get {
                return ResourceManager.GetString("DownloadMedical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string DownloadNonMedical {
            get {
                return ResourceManager.GetString("DownloadNonMedical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo Client.
        /// </summary>
        internal static string FinancialInstitution {
            get {
                return ResourceManager.GetString("FinancialInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 09/02/2023.
        /// </summary>
        internal static string From_Upload_Date {
            get {
                return ResourceManager.GetString("From_Upload_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 83.
        /// </summary>
        internal static string JobID {
            get {
                return ResourceManager.GetString("JobID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28/02/2023.
        /// </summary>
        internal static string To_Upload_Date {
            get {
                return ResourceManager.GetString("To_Upload_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Bulk Upload.
        /// </summary>
        internal static string ViewBulkUploadTitle {
            get {
                return ResourceManager.GetString("ViewBulkUploadTitle", resourceCulture);
            }
        }
    }
}
